language: node_js
node_js:
  - 10.16.3
install:
  - npm install
services: mongodb
env:
  - MONGODB_URL=mongodb+srv://demola:demola@cluster0-yxizt.mongodb.net/messages?retryWrites=true&w=majority     MONGODB_URI_TEST=mongodb+srv://demola:demola@cluster0-yxizt.mongodb.net/test-messages?retryWrites=true&w=majority
script:
  - npm run test
branches:
  only:
    - master
